src/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todofeature.urls", namespace="todofeature")),
]

src/todofeature/urls.py
from django.urls import path
from todofeature.views import todo_list_view, todo_add_view


app_name = "todofeature"

urlpatterns = [
    path("",todo_list_view, name="todo_list"),
    path("todo-add/", todo_add_view, name="todo_add"),

]

src/todofeature/models.py
from django.db import models
class TimestampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)#you don't have 
    modified_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True



class Category(models.Model):
    name = models.CharField(max_length=255)
    

    def __str__(self):
        return self.name


class Label(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Priority(models.TextChoices):
    LOWEST ="lowest", "Lowest"
    LOW = "low", "Low"
    MEDIUM = "medium", "Medium"
    HIGH = "high", "High"
    HIGHEST = "highest","Highest"


class Task(TimestampModel):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="todoimage",blank=True, null=True)
    task_date = models.DateField(blank=True, null=True)  
    priority = models.CharField(
        max_length=100,
        choices=Priority.choices,
        default=Priority.LOWEST
    )    

    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        blank=True, 
        null=True
        
    )
    Label = models.ManyToManyField(Label, blank=True)

    def __str__(self):
        return self.name 

src/useraccount/models.py
from django.db import models

# Create your models here.

src/todofeature/forms.py
from django import forms
from todofeature.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        #exclude = ("image",) 

    def clean_field(self):
        name = self.cleaned_data.get["name"]
        if name.isdigit():
             raise forms.ValidationError("Name can not be number")
        return name
            
        

src/todofeature/views.py
from django.shortcuts import render
from django.urls import reverse
from todofeature.models import Task
from todofeature.forms import TaskForm
from django.http import HttpResponseRedirect


def todo_list_view(request):
    return render(request, "todo_list.html")



def todo_add_view(request):
   form = TaskForm(request.POST or None)
   if form.is_valid():
    # print(form.cleaned_data)]
    form.save()
    return HttpResponseRedirect(reverse("todofeature:todo_list"))
   return render(request, "add_todo.html",{"form": form})
 

src/useraccount/views.py
from django.shortcuts import render

# Create your views here.

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if title %}
            {{ title}}
        {% else %}
            TODO
        {% endif %}
    </title>
    {% block stylesheet %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock stylesheet%}
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

src/templates/base_site.html
{% extends 'base.html' %}

{% block content %}

    
    {% include 'navbar.html' %}

    {% block maincontent %}
    {% endblock maincontent %}

{% endblock content %}

src/templates/navbar.html
<ul>
    <li>
        <a href="{% url 'todofeature:todo_list' %}">List ToDo</a>

        

    </li>
        <li>
           <a href="{% url 'todofeature:todo_add' %}">Add Tools</a>
        </li>
</ul>

src/todofeature/templates/add_todo.html
{% extends 'base_site.html' %}

{% block maincontent %}
<form method="post" action="">{% csrf_token %}
    {{ form.as_p }}
    {% comment %} <input  type="text" name="title" /> {% endcomment %}
    <input type="submit" name="submit" value="Submit" />
</form>

{% endblock maincontent %}

src/todofeature/templates/todo_list.html
{% extends 'base_site.html' %}

{% block maincontent %}
<h1>My todo page</h1>

{% endblock maincontent %}